# Generated by Django 3.1.3 on 2020-11-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
