# Generated by Django 3.1.3 on 2020-11-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0002_list_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='category',
        ),
    ]
