# Generated by Django 3.1.3 on 2020-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0003_remove_list_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='completed',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
