# Generated by Django 3.1.3 on 2020-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0004_auto_20201122_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('leader', models.CharField(max_length=32)),
            ],
        ),
    ]
