# Generated by Django 3.1.3 on 2020-12-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0008_auto_20201211_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='retro',
            name='voting',
            field=models.BooleanField(default=False),
        ),
    ]
