# Generated by Django 3.1.3 on 2020-12-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0011_list_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='retro',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
