# Generated by Django 3.1.3 on 2021-03-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0012_retro_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='completed',
            new_name='category',
        ),
    ]
