# Generated by Django 3.1.3 on 2021-03-05 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0013_auto_20210301_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='retro',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
