# Generated by Django 3.1.3 on 2021-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0014_retro_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retro',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
