# Generated by Django 3.1.3 on 2021-04-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0015_auto_20210305_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retro',
            name='leader',
        ),
    ]
