# Generated by Django 3.1.3 on 2022-07-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0016_remove_retro_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='retro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='retro_app.retro'),
        ),
    ]
