# Generated by Django 3.1.3 on 2022-07-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0018_auto_20220717_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
    ]
