# Generated by Django 3.1.3 on 2022-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0019_auto_20220721_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='body',
            field=models.TextField(),
        ),
    ]
