# Generated by Django 3.1.3 on 2022-09-24 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retro_app', '0020_auto_20220924_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='card_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
