# Generated by Django 3.1.3 on 2022-10-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_app', '0021_auto_20220924_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
    ]
